import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const names=[...readFileSync('playground/demos.tsx','utf8').matchAll(/export function (\w+)Demo/g)].map(m=>m[1]);
const expectVisible=async l=>assert.ok(await l.isVisible(),'trigger must stay visible');
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
try {
 for(const name of names){await page.goto(`http://localhost:5173/#${name}`);await page.getByRole('heading',{name,exact:true,level:1}).waitFor();assert.equal(await page.getByText('Components page crashed').count(),0,`${name} crashed`);await page.locator('.detail-preview').waitFor();}
 console.log(`PASS: ${names.length} component routes render.`);
 await page.goto('http://localhost:5173/#Message');await page.locator('.detail-preview').getByRole('button',{name:'Success message'}).click();await page.getByText('Changes saved',{exact:true}).waitFor();
 await page.goto('http://localhost:5173/#Modal');await page.getByRole('button',{name:'Open modal',exact:true}).click();await page.getByRole('dialog').waitFor();await page.waitForTimeout(150);await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await page.getByRole('dialog').count(),0);
 await page.goto('http://localhost:5173/#Select');await page.getByRole('combobox').click();await page.getByRole('option',{name:'React',exact:true}).click();assert.match(await page.getByRole('combobox').innerText(),/React/);
 await page.goto('http://localhost:5173/#Cascader');await page.locator('.detail-preview').getByRole('button').first().click();await page.getByRole('option',{name:'Design',exact:true}).click();await page.getByRole('option',{name:'Components',exact:true}).click();assert.match(await page.locator('.detail-preview').innerText(),/Design \/ Components/);
 await page.goto('http://localhost:5173/#Transfer');await page.getByRole('option',{name:'Design',exact:true}).focus();await page.keyboard.press('Space');await page.getByRole('button',{name:'Move to target'}).click();await page.getByRole('listbox',{name:'Selected'}).getByText('Design',{exact:true}).waitFor();
 await page.goto('http://localhost:5173/#Splitter');const separator=page.getByRole('separator',{name:'Resize panes'});await separator.focus();await page.keyboard.press('ArrowRight');assert.equal(await separator.getAttribute('aria-valuenow'),'52');
 await page.goto('http://localhost:5173/#Grid');const cols=await page.locator('.detail-preview').evaluate(el=>{const row=el.firstElementChild;return [...row.children].map(c=>({span:parseInt(c.textContent),ratio:c.getBoundingClientRect().width/row.getBoundingClientRect().width}))});assert.ok(cols.length>1&&cols.every(c=>Math.abs(c.ratio-c.span/24)<.01),`each Col must be span/24 of its Row: ${JSON.stringify(cols)}`);
 await page.goto('http://localhost:5173/#Listy');assert.ok(await page.locator('.detail-preview [role="listitem"]').count()<30);await page.locator('[data-radix-scroll-area-viewport]').evaluate(el=>{el.scrollTop=47500});await page.waitForTimeout(100);assert.ok((await page.locator('.detail-preview [role="listitem"]').first().getAttribute('aria-posinset'))>900);
 await page.goto('http://localhost:5173/#Table');await page.getByRole('textbox',{name:'Filter projects'}).fill('Brand');assert.equal(await page.locator('.detail-preview tbody tr').count(),1);await page.getByText('Brand guidelines',{exact:true}).waitFor();
 await page.goto('http://localhost:5173/#Upload');await page.locator('input[type="file"]').setInputFiles({name:'example.txt',mimeType:'text/plain',buffer:Buffer.from('Example')});await page.locator('.detail-preview').getByText('example.txt',{exact:true}).waitFor();
 await page.goto('http://localhost:5173/#Tour');await page.getByRole('button',{name:'Start tour',exact:true}).click();await page.getByRole('dialog').waitFor();await page.waitForTimeout(150);await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByRole('heading',{name:'Make it yours',exact:true}).waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await page.getByRole('dialog').count(),0);
 await page.goto('http://localhost:5173/#overview');await page.getByRole('textbox',{name:'Search components'}).fill('slider');assert.equal(await page.locator('.nav-group a').count(),1);await page.locator('.nav-group a').click();await page.getByRole('heading',{name:'Slider',exact:true,level:1}).waitFor();
 await page.getByRole('button',{name:'Switch to dark mode',exact:true}).click();await page.waitForTimeout(250);assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.reload();await page.locator('html[data-theme="dark"]').waitFor({state:'attached'});
 console.log('PASS: feedback, dialogs, selections, transfer, grid, splitter, virtualization, table filtering, uploads, tour, search and theme persistence.');
 // --- regressions for the fixed bugs ---
 await page.goto('http://localhost:5173/#Segmented');const active=page.locator('.detail-preview button').first();await active.click();assert.equal(await active.getAttribute('data-state'),'on','clicking the active segment must not deselect it');
 await page.goto('http://localhost:5173/#Message');assert.ok(await page.evaluate(async()=>{const m=await import('/src/index.ts');const before=document.querySelectorAll('li[data-state]').length;m.message.success('x');m.message.info('y');m.message.warning('z');await new Promise(r=>setTimeout(r,400));return m.message._api!==null&&document.querySelectorAll('li[data-state]').length===before+3}),'the imperative message helper must be bound and render toasts');
 await page.goto('http://localhost:5173/#Affix');assert.ok(await page.evaluate(async()=>{const sc=[...document.querySelectorAll('.detail-preview div')].find(d=>getComputedStyle(d).overflowY==='auto');const a=sc.firstElementChild;sc.scrollTop=200;await new Promise(r=>setTimeout(r,200));return Math.abs(a.getBoundingClientRect().top-sc.getBoundingClientRect().top)<2}),'Affix must stick to the top of its scroll container');
 await page.goto('http://localhost:5173/#Watermark');assert.ok(await page.evaluate(()=>{const el=document.querySelector('.detail-preview [style*="mask-image"]');const url=getComputedStyle(el).webkitMaskImage.slice(5,-2);return decodeURIComponent(url).includes('&#38;')&&new Promise(r=>{const i=new Image();i.onload=()=>r(true);i.onerror=()=>r(false);i.src=url})}),'a watermark label containing & must stay valid SVG');
 assert.equal(await page.evaluate(async()=>{const{space}=await import('/src/utils/space.ts');const d=document.createElement('div');document.body.append(d);d.style.columnGap=space(24);const v=getComputedStyle(d).columnGap;d.remove();return v}),'24px','an off-scale spacing step must fall back to pixels, not drop the rule');
 assert.equal(await page.evaluate(async()=>{const{inputSizeClass}=await import('/src/components/data-entry/Input.tsx');const d=document.createElement('div');d.className=inputSizeClass.md;document.body.append(d);const v=getComputedStyle(d).minHeight;d.remove();return v}),'36px','size="md" must be its own size, not an alias for lg');
 await page.goto('http://localhost:5173/#App');const notify=page.getByRole('button',{name:'Show notification',exact:true});await notify.click();await notify.click();await notify.click();await page.waitForTimeout(200);assert.equal(await page.locator('[role="region"][aria-label^="Notifications"] li',{hasText:'Export ready'}).count(),3,'notifications must stack');await page.waitForTimeout(4800);assert.equal(await page.locator('[role="region"][aria-label^="Notifications"] li',{hasText:'Export ready'}).count(),0,'notifications must auto-dismiss');
 await page.goto('http://localhost:5173/#Rate');assert.equal(await page.locator('.detail-preview [role="slider"]').count(),0);assert.equal(await page.locator('.detail-preview [role="group"]').getAttribute('aria-label'),'Rating');assert.equal(await page.getByRole('button',{name:'4 stars'}).getAttribute('aria-pressed'),'true');
 await page.goto('http://localhost:5173/#Tree');assert.ok(await page.locator('.detail-preview [role="group"]').count()>0,'child treeitems must sit in a role=group');
 await page.goto('http://localhost:5173/#Popconfirm');const confirmTrigger=page.getByRole('button',{name:'Remove item',exact:true});await confirmTrigger.click();await page.getByText('Remove this item?',{exact:true}).waitFor();await expectVisible(page.locator('.detail-preview button[aria-haspopup="dialog"]',{hasText:'Remove item'}));await page.getByRole('button',{name:'Remove',exact:true}).click();await page.getByText('Item removed',{exact:true}).waitFor();
 await page.goto('http://localhost:5173/#Drawer');const drawerOpener=page.getByRole('button',{name:'Open controlled drawer',exact:true});await drawerOpener.focus();await page.keyboard.press('Enter');await page.getByRole('dialog').waitFor();await page.waitForTimeout(150);assert.ok(await page.getByRole('dialog').evaluate(d=>d.contains(document.activeElement)),'a drawer takes focus as it opens');await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});await page.waitForTimeout(50);assert.ok(await drawerOpener.evaluate(b=>b===document.activeElement),'a drawer with no trigger gives focus back to the control that opened it');
 await page.goto('http://localhost:5173/#Drawer');await page.getByRole('button',{name:'Open drawer',exact:true}).click();const drawer=page.getByRole('dialog',{name:'Project details'});await drawer.waitFor();await drawer.getByRole('combobox',{name:'Status'}).click();await page.getByRole('option',{name:'Active',exact:true}).click({timeout:5000});assert.match(await drawer.getByRole('combobox',{name:'Status'}).innerText(),/Active/,'a Select inside a Drawer must take a mouse pick');assert.ok(await drawer.isVisible(),'picking an option must not close the drawer');await page.keyboard.press('Escape');await drawer.waitFor({state:'hidden'});
 await page.goto('http://localhost:5173/#Drawer');await page.getByRole('button',{name:'Open drawer',exact:true}).click();const plainDrawer=page.getByRole('dialog',{name:'Project details'});await plainDrawer.waitFor();assert.equal(await plainDrawer.getByRole('button',{name:'Close drawer',exact:true}).count(),1,'a drawer with no closeLabel keeps the English default');await page.keyboard.press('Escape');await plainDrawer.waitFor({state:'hidden'});await page.getByRole('button',{name:'Open controlled drawer',exact:true}).click();const labelled=page.getByRole('dialog',{name:'Rename project'});await labelled.waitFor();assert.equal(await labelled.getByRole('button',{name:'Close drawer',exact:true}).count(),0,'closeLabel replaces the default name rather than sitting beside it');await labelled.getByRole('button',{name:'Close without renaming',exact:true}).click({timeout:5000});await labelled.waitFor({state:'hidden'});
 console.log('PASS: segmented selection, message helper, affix stickiness, watermark escaping, spacing fallback, md sizing, notification stacking, rate/tree roles, modal popconfirm, drawer focus return, select inside a drawer and drawer close label.');
 await page.goto('http://localhost:5173/#Switch');for(const state of ['checked','unchecked']){const inset=await page.locator(`button[role="switch"][data-state="${state}"]`).first().evaluate(sw=>{const s=sw.getBoundingClientRect(),t=sw.firstElementChild.getBoundingClientRect();return [t.left-s.left,s.right-t.right,t.top-s.top,s.bottom-t.bottom].map(n=>Math.round(n))});assert.ok(inset.every(n=>n>=2),`switch thumb escapes its track when ${state}: ${inset}`);}
 assert.equal(await page.evaluate(()=>{const b=document.createElement('button');document.body.append(b);const v=getComputedStyle(b).padding;b.remove();return v}),'0px','the reset must neutralise UA button padding');
 await page.goto('http://localhost:5173/#Notification');assert.deepEqual(await page.getByRole('button',{name:'Dismiss notification'}).evaluate(b=>{const r=b.getBoundingClientRect();return [Math.round(r.width),Math.round(r.height)]}),[44,44],'close buttons need a 44px hit target of their own');
 const markPath=await page.locator('.brand-mark svg path').first().getAttribute('d');assert.ok(markPath,'the sidebar brand mark uses the logo');
 assert.ok(await page.evaluate(d=>fetch('/favicon.svg').then(r=>r.text()).then(t=>t.includes('viewBox="0 0 200 200"')&&t.includes(d)),markPath),'the favicon is the same Phase mark as the sidebar');
 console.log('PASS: switch thumb containment, button padding reset, close-button hit targets and logo wiring.');
 await page.goto('http://localhost:5173/#Masonry');const bricks=await page.locator('.detail-preview > div').evaluate(root=>{const rr=root.getBoundingClientRect();const col=x=>Math.round((x-rr.left)/((rr.width+12)/3));return [...root.children].map(w=>{const c=w.firstElementChild.getBoundingClientRect();return {t:w.textContent.trim(),col:col(c.left),y:Math.round(c.top-rr.top),bottom:Math.round(c.bottom-rr.top)}})});
 assert.deepEqual(bricks.slice(0,3).map(b=>b.col),[0,1,2],`masonry must run in reading order, got ${JSON.stringify(bricks.map(b=>b.col))}`);
 assert.deepEqual(bricks.slice(0,3).map(b=>b.y),[0,0,0],'the first row of a masonry starts flush');
 for(const b of bricks.slice(3)){const above=bricks.filter(o=>o.col===b.col&&o.y<b.y).sort((x,y)=>y.bottom-x.bottom)[0];assert.ok(above&&b.y-above.bottom===12,`"${b.t}" must pack one gap under "${above&&above.t}", got ${above&&b.y-above.bottom}`);}
 assert.equal(await page.locator('.detail-preview > div').evaluate(r=>getComputedStyle(r).marginBottom),'-12px','the phantom trailing row is trimmed');
 await page.goto('http://localhost:5173/#Transfer');assert.deepEqual(await page.locator('.detail-preview [role="option"] span').evaluateAll(ss=>ss.map(s=>{const p=s.closest('[role="listbox"]').parentElement.getBoundingClientRect();return Math.round(s.getBoundingClientRect().right-p.right)}).filter(n=>n>0)),[],'transfer labels must stay inside their panel');
 console.log('MASONRY/TRANSFER: reading order, shortest-column packing and panel containment verified.');
 await page.goto('http://localhost:5173/#Menu');await page.getByRole('button',{name:'Projects'}).click();await page.getByRole('button',{name:'Website'}).waitFor();
 const menuGeom=await page.locator('.detail-preview nav').evaluate(nav=>{const px=v=>parseFloat(v);const root=getComputedStyle(nav);const list=getComputedStyle(nav.firstElementChild);const rows=[...nav.querySelectorAll('a,button')].map(el=>{const r=el.getBoundingClientRect();return {left:Math.round(r.left),width:Math.round(r.width),radius:getComputedStyle(el).borderRadius}});return {rootRadius:px(root.borderRadius),listPad:px(list.paddingLeft),itemRadius:px(rows[0].radius),rows,nestedNavs:nav.querySelectorAll('nav').length}});
 assert.deepEqual([menuGeom.rootRadius,menuGeom.itemRadius],[0,0],`menu corners must be square (concentric by construction): root ${menuGeom.rootRadius}, rows ${menuGeom.itemRadius}`);
 assert.equal(menuGeom.nestedNavs,0,'a submenu must not render a card inside the card');
 assert.equal(new Set(menuGeom.rows.map(r=>`${r.left}:${r.width}:${r.radius}`)).size,1,'every menu row shares one edge, width and radius at any depth');
 await page.goto('http://localhost:5173/#Calendar');
 assert.ok(await page.locator('.detail-preview [data-day]').count()>=28,'the calendar renders its day cells');assert.deepEqual(await page.locator('.detail-preview [data-day]').evaluateAll(ds=>ds.map(d=>{const c=getComputedStyle(d);return c.borderTopWidth!=='0px'&&parseFloat(c.borderTopLeftRadius)>0?d.textContent:null}).filter(Boolean)),[],'a one-sided border plus a radius leaves arc stubs at every join');
 const dayAlign=await page.locator('.detail-preview [data-day]:has(span + span:not(:empty))').first().evaluate(d=>{const kids=d.querySelectorAll('span');return Math.round(kids[0].getBoundingClientRect().left-kids[1].getBoundingClientRect().left)});
 assert.equal(dayAlign,0,`the date number and its event must share a left edge, off by ${dayAlign}px`);
 for(const theme of ['light','dark']){await page.goto('http://localhost:5173/#Segmented');const cur=await page.locator('html').getAttribute('data-theme');if(cur!==theme){await page.getByRole('button',{name:`Switch to ${theme} mode`}).click();await page.waitForTimeout(250)}
  const lum=await page.locator('.detail-preview [data-state="on"]').evaluate(el=>{const sum=v=>v.match(/\d+/g).slice(0,3).reduce((a,b)=>a+ +b,0);return {thumb:sum(getComputedStyle(el).backgroundColor),track:sum(getComputedStyle(el.parentElement).backgroundColor)}});
  assert.ok(Math.abs(lum.thumb-lum.track)>=300,`the selected segment must stand clear of its track in ${theme}, got thumb ${lum.thumb} on track ${lum.track}`);}
 console.log('PASS: menu square corners, calendar cell borders and alignment, segmented thumb in both themes.');




 for(const width of [390,820,1440]){await page.setViewportSize({width,height:900});for(const route of ['overview','DatePicker','Table','Transfer','tokens']){await page.goto(`http://localhost:5173/#${route}`);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${route} overflows at ${width}px`);}}
 console.log('PASS: no horizontal overflow at mobile, tablet and desktop sizes.');
 assert.deepEqual(errors,[]);console.log('PASS: no browser errors.');
} finally {await browser.close();}
